name: Create Pull Request
on:
  push:
    tags:
      - '*'

jobs:
    pull-request:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      # https://github.com/repo-sync/pull-request
      # if the tag from develop , then create
      # a PR to "master" branch
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: github.event.base_ref == 'refs/heads/develop'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # be explicit about branches
          source_branch: "develop"
          destination_branch: "master"
          pr_title: "[Bot] develop to master auto PR"
          pr_body: ":robot: Automated PR from **develop** to **master**"
          pr_label: "version"

